apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: level-up-accounts-api-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/name: level-up-accounts-api
    app.kubernetes.io/instance: development
    app.kubernetes.io/environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/thongnv701/level-up-accounts.git
    targetRevision: HEAD
    path: k8s-manifests/overlays/dev
    kustomize:
      commonAnnotations:
        argocd.argoproj.io/sync-wave: "3" # Deploy after External Secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: levelupaccounts-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  