apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: level-up-accounts-api-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    notifications.argoproj.io/subscribe.on-deployment-started.slack: ""
    notifications.argoproj.io/subscribe.on-deployment-failed.slack: ""
  labels:
    app.kubernetes.io/name: level-up-accounts-api
    app.kubernetes.io/instance: production
    app.kubernetes.io/environment: prod
spec:
  project: default
  source:
    repoURL: https://github.com/thongnv701/level-up-accounts.git
    targetRevision: HEAD
    path: k8s-manifests/overlays/prod
    kustomize:
      commonAnnotations:
        argocd.argoproj.io/sync-wave: "3" # Deploy after External Secrets and Nginx Ingress
      # No patches needed - External Secrets Operator creates github-auth secret automatically
  destination:
    server: https://kubernetes.default.svc
    namespace: levelupaccounts-prod
  syncPolicy:
    # Manual sync for production safety - no automated deployments
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - RespectIgnoreDifferences=true
    # Uncomment for automated sync if desired:
    # automated:
    #   prune: true
    #   selfHeal: true
  # No ignoreDifferences needed - External Secrets Operator manages github-auth secret  