apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: level-up-accounts-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thongnv701/IaC_LevelUpAccounts.git
    targetRevision: HEAD
    path: k8s/api
    kustomize:
      images:
        - thongnv0701/levelupaccount:latest
      commonAnnotations:
        argocd.argoproj.io/sync-wave: "2" # Deploy after External Secrets Operator and config
      # No patches needed - External Secrets Operator creates github-auth secret automatically
  destination:
    server: https://kubernetes.default.svc
    namespace: level-up-accounts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # No ignoreDifferences needed - External Secrets Operator manages github-auth secret