apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: level-up-accounts-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thongnv701/level-up-accounts.git
    targetRevision: HEAD
    path: k8s
    kustomize:
      images:
        - docker.io/thongnv0701/levelupaccounts=thongnv0701/levelupaccounts:latest
      commonAnnotations:
        argocd.argoproj.io/sync-wave: "3" # Deploy after External Secrets and Nginx Ingress
      # No patches needed - External Secrets Operator creates github-auth secret automatically
  destination:
    server: https://kubernetes.default.svc
    namespace: level-up-accounts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  # No ignoreDifferences needed - External Secrets Operator manages github-auth secret