apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials-secret
  namespace: cert-manager
type: Opaque
stringData:
  secret-access-key: YOUR_AWS_SECRET_ACCESS_KEY  # Replace with your AWS secret key 