apiVersion: apps/v1
kind: Deployment
metadata:
  name: level-up-accounts-api
  namespace: level-up-accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: level-up-accounts-api
  template:
    metadata:
      labels:
        app: level-up-accounts-api
    spec:
      initContainers:
      - name: fetch-config
        image: curlimages/curl:latest
        command: 
        - /bin/sh
        - -c
        - |
          echo "Token first 4 chars: $(head -c 4 /etc/github/token)"
          curl -v -H "Authorization: token $(cat /etc/github/token)" \
               -H "Accept: application/vnd.github.v3.raw" \
               -L https://api.github.com/repos/thongnv701/secret-key/contents/levelupaccounts/appsettings.json \
               -o /config/appsettings.json
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: github-auth
          mountPath: /etc/github
          readOnly: true
      containers:
      - name: api
        image: docker.io/thongnv0701/levelupaccounts:latest
        command: ["dotnet"]
        args: ["LevelUpAccounts.API.dll"]
        workingDir: /app
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ASPNETCORE_CONFIGURATION_PATH
          value: "/app/config/appsettings.json"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: config-volume
        emptyDir: {}
      - name: github-auth
        secret:
          secretName: github-auth
          items:
          - key: token
            path: token 