apiVersion: apps/v1
kind: Deployment
metadata:
  name: level-up-accounts-api
  namespace: level-up-accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: level-up-accounts-api
  template:
    metadata:
      labels:
        app: level-up-accounts-api
    spec:
      initContainers:
      - name: fetch-config
        image: curlimages/curl:latest
        command: 
        - /bin/sh
        - -c
        - |
          curl -H "Authorization: token $(cat /etc/github/token)" \
               -H "Accept: application/vnd.github.v3.raw" \
               -L https://api.github.com/repos/thongnv701/secret-key/contents/levelupaccounts/appsettings.json \
               -o /app/appsettings.json
        volumeMounts:
        - name: app-config
          mountPath: /app
        - name: github-auth
          mountPath: /etc/github
          readOnly: true
      containers:
      - name: api
        image: docker.io/thongnv0701/levelupaccounts:latest
        command: ["/bin/sh"]
        args: ["-c", "echo '=== Contents of /app ===' && ls -la /app && echo '=== Contents of /app/publish ===' && ls -la /app/publish 2>/dev/null || echo 'publish directory not found' && echo '=== Contents of /app/build ===' && ls -la /app/build 2>/dev/null || echo 'build directory not found' && echo '=== .NET Info ===' && dotnet --info && sleep 3600"]
        workingDir: /app
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-config
          mountPath: /app
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      volumes:
      - name: app-config
        emptyDir: {}
      - name: github-auth
        secret:
          secretName: github-auth
          items:
          - key: token
            path: token 