apiVersion: apps/v1
kind: Deployment
metadata:
  name: level-up-accounts-api
  namespace: level-up-accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: level-up-accounts-api
  template:
    metadata:
      labels:
        app: level-up-accounts-api
    spec:
      initContainers:
      - name: fetch-config
        image: curlimages/curl:latest
        command: 
        - /bin/sh
        - -c
        - |
          curl -H "Authorization: token $(cat /etc/github/token)" \
               -H "Accept: application/vnd.github.v3.raw" \
               -L https://github.com/thongnv701/secret-key/blob/main/levelupaccounts/appsettings.json \
               -o /app/appsettings.json
        volumeMounts:
        - name: app-config
          mountPath: /app
        - name: github-auth
          mountPath: /etc/github
          readOnly: true
      containers:
      - name: api
        image: docker.io/thongnv0701/levelupaccounts:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-config
          mountPath: /app
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: app-config
        emptyDir: {}
      - name: github-auth
        secret:
          secretName: github-auth
          items:
          - key: token
            path: token 