apiVersion: apps/v1
kind: Deployment
metadata:
  name: level-up-accounts-api
  namespace: level-up-accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: level-up-accounts-api
  template:
    metadata:
      labels:
        app: level-up-accounts-api
    spec:
      initContainers:
      - name: fetch-config
        image: curlimages/curl:latest
        command: 
        - /bin/sh
        - -c
        - |
          echo "=== Debugging Secret Mount ==="
          echo "Checking /etc/github directory..."
          ls -la /etc/github
          echo "Checking token file..."
          if [ -f /etc/github/token ]; then
            echo "Token file exists"
            TOKEN=$(cat /etc/github/token)
            echo "Token length: ${#TOKEN}"
            echo "Token first 4 chars: ${TOKEN:0:4}"
            if [ -z "$TOKEN" ]; then
              echo "Token is empty!"
              exit 1
            fi
          else
            echo "Token file does not exist!"
            exit 1
          fi
          echo "=== Attempting to fetch config ==="
          curl -v -H "Authorization: token $TOKEN" \
               -H "Accept: application/vnd.github.v3.raw" \
               -L https://api.github.com/repos/thongnv701/secret-key/contents/levelupaccounts/appsettings.json \
               -o /config/appsettings.json
          if [ $? -eq 0 ]; then
            echo "=== Config file contents ==="
            cat /config/appsettings.json
          else
            echo "Failed to fetch config file"
            exit 1
          fi
        volumeMounts:
        - name: config-volume
          mountPath: /config
        - name: github-autha
          mountPath: /etc/github
          readOnly: true
      containers:
      - name: api
        image: docker.io/thongnv0701/levelupaccounts:latest
        command: ["dotnet"]
        args: ["LevelUpAccounts.API.dll"]
        workingDir: /app
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        - name: github-autha
          mountPath: /etc/github
          readOnly: true
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ASPNETCORE_CONFIGURATION_PATH
          value: "/app/config/appsettings.json"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        # readinessProbe:
        #   httpGet:
        #     path: /api/v1/ping
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /api/v1/ping
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
      volumes:
      - name: config-volume
        emptyDir: {}
      - name: github-autha
        secret:
          secretName: github-autha
          items:
          - key: token
            path: token 