apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # github-secret.yaml removed - External Secrets Operator creates this secret

images:
  - name: docker.io/thongnv0701/levelupaccounts
    newName: thongnv0701/levelupaccounts
    newTag: latest 