apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - github-secret.yaml

images:
  - name: level-up-accounts-api
    newName: thongnv0701/levelupaccount
    newTag: latest 