apiVersion: v1
kind: Service
metadata:
  name: level-up-accounts-api
  namespace: level-up-accounts
spec:
  selector:
    app: level-up-accounts-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 