apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-repo-external
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: backend-repo-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/thongnv701/level-up-accounts.git
        password: "{{ .token }}"
        username: not-used
  data:
  - secretKey: token
    remoteRef:
      key: level-up-accounts/github-token
      property: token 