# AWS credentials secret is created by the GitHub workflow
# This file only contains the SecretStore and ExternalSecret configurations
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: level-up-accounts
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-southeast-1
      auth:
        secretRef:
          accessKeyID:
            name: aws-credentials
            key: access-key-id
            namespace: level-up-accounts
          secretAccessKey:
            name: aws-credentials
            key: secret-access-key
            namespace: level-up-accounts
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-auth-external
  namespace: level-up-accounts
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: github-auth
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: level-up-accounts/github-token
      property: token 