apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-repo-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/thongnv701/IaC_LevelUpAccounts.git
    targetRevision: HEAD
    path: k8s/external-secrets
    kustomize:
      commonAnnotations:
        argocd.argoproj.io/sync-wave: "1" # Deploy before main applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 