apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1" # Deploy after External Secrets Operator
spec:
  project: default
  source:
    repoURL: https://github.com/thongnv701/IaC_LevelUpAccounts.git
    targetRevision: main
    path: k8s/external-secrets/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: levelupaccounts-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 