apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.57.4
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - grafana.thongit.space
          tls:
            - hosts:
                - grafana.thongit.space
              secretName: grafana-tls
          annotations:
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"

        adminPassword: "admin-password"

        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-operated.monitoring.svc.cluster.local:9090
                access: proxy
                isDefault: true

        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: 'kubernetes'
                orgId: 1
                folder: 'Kubernetes'
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/kubernetes

        # Kubernetes dashboards
        dashboards:
          kubernetes:
            # Kubernetes Capacity Planning
            k8s-capacity-planning:
              gnetId: 5228
              revision: 1
              datasource: Prometheus
              
            # Kubernetes Cluster
            k8s-cluster:
              gnetId: 7249
              revision: 1
              datasource: Prometheus
              
            # Kubernetes Pod Resources
            k8s-pod-resources:
              gnetId: 11199
              revision: 1
              datasource: Prometheus
              
            # Node Exporter Full
            node-exporter:
              gnetId: 1860
              revision: 27
              datasource: Prometheus
              
            # Kubernetes All Namespaces
            k8s-all-namespaces:
              gnetId: 15757
              revision: 23
              datasource: Prometheus

        # Enable persistent storage
        persistence:
          enabled: true
          size: 5Gi

        serviceAccount:
          create: true
          name: grafana
          
        service:
          type: ClusterIP
          port: 80
          
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true