fullnameOverride: argocd

crds:
  install: true
configs:
  params:
    server.host: argocd.thongit.space
    
redis:
  enabled: true
  image:
    tag: "6.2.4"
  service:
    port: 6379

repoServer:
  replicas: 1

applicationSet:
  enabled: true
  replicas: 1

dex:
  enabled: true
  extraArgs:
    - --disable-tls 

server:
  extraArgs: 
    - --dex-server
    - http://argocd-dex-server.argocd.svc.cluster.local:5556
    - --dex-server-plaintext 
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - ""
    paths:
      - /
    # extraHosts:
    #   - name: argocd.thongit.space
    #     paths:
    #       - /
    tls:
      - secretName: argocd-tls-certificate
        hosts:
          - argocd.thongit.space
  redis:
    host: argocd-redis