global:
  domain: argocd.thongit.space

fullnameOverride: argocd

crds:
  install: true

redis:
  enabled: true

repoServer:
  replicas: 1

applicationSet:
  enabled: true
  replicas: 1

dex:
  enabled: true
  extraArgs:
    - --disable-tls 

server:
  extraArgs: 
    - --dex-server
    - http://argocd-dex-server.argocd.svc.cluster.local:5556
    - --dex-server-plaintext 
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"  # Only if using cert-manager
    hosts:
      - argocd.thongit.space  # Explicit hostname
    paths:
      - /
    tls:
      - hosts:
          - argocd.thongit.space
        secretName: argocd-tls

configs:
  cm:
    url: https://argocd.thongit.space
    exec.enabled: true
    admin.enabled: true

  params:
    server.insecure: false  # Should be false when using TLS

controller:
  metrics:
    enabled: true