name: Terraform Destroy

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    environment: terraform

    env:
      TF_VAR_allowed_cidr: ${{ secrets.ALLOWED_CIDR }}
      TF_VAR_private_key_content: ${{ secrets.PRIVATE_KEY_CONTENT }}
      TF_VAR_rds_endpoint: ${{ secrets.RDS_ENDPOINT }}
      TF_VAR_rds_username: ${{ secrets.RDS_USERNAME }}
      TF_VAR_rds_password: ${{ secrets.RDS_PASSWORD }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_route53_zone_id: ${{ secrets.ROUTE53_ZONE_ID }}
      TF_VAR_github_token: ${{ secrets.GIT_TOKEN }}
      TF_VAR_master_instance_type: ${{ secrets.MASTER_INSTANCE_TYPE }}
      TF_VAR_worker_instance_type: ${{ secrets.WORKER_INSTANCE_TYPE }}
      TF_VAR_worker_count: ${{ secrets.WORKER_COUNT }}
      AWS_DEFAULT_REGION: "ap-southeast-1"

    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.3.0"

      - name: Ensure kubeconfig directory exists
        run: mkdir -p ./terraform/modules/compute

      - name: Download kubeconfig from S3
        run: aws s3 cp s3://my-terraform-backup-0701/kubeconfig /home/runner/work/IaC_LevelUpAccounts/IaC_LevelUpAccounts/terraform/modules/compute/kubeconfig || true

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Debug kubeconfig
        run: |
          ls -l ./terraform/modules/compute/
          cat ./terraform/modules/compute/kubeconfig || true
      - name: Terraform Destroy
        continue-on-error: true
        working-directory: ./terraform
        run: terraform destroy -auto-approve

      - name: Delete Terraform state from S3
        run: |
            aws s3 rm s3://my-terraform-backup-0701/levelupaccounts/terraform.tfstate
            aws s3 rm s3://my-terraform-backup-0701/levelupaccounts/terraform.tfstate.backup || true
            aws s3 rm s3://my-terraform-backup-0701/kubeconfig || true
            aws s3 rm s3://my-terraform-backup-0701/argocd-admin-password.txt || true